//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class plist
{

    private object itemField;

    private ItemChoiceType1 itemElementNameField;

    private string versionField;

    public plist()
    {
        this.versionField = "1.0";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("array", typeof(array))]
    [System.Xml.Serialization.XmlElementAttribute("data", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("date", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("dict", typeof(dict))]
    [System.Xml.Serialization.XmlElementAttribute("false", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("integer", typeof(string), DataType = "integer")]
    [System.Xml.Serialization.XmlElementAttribute("real", typeof(real))]
    [System.Xml.Serialization.XmlElementAttribute("string", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("true", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public object Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType1 ItemElementName
    {
        get
        {
            return this.itemElementNameField;
        }
        set
        {
            this.itemElementNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1.0")]
    public string version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class array
{

    private object[] itemsField;

    private ItemChoiceType[] itemsElementNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("array", typeof(array))]
    [System.Xml.Serialization.XmlElementAttribute("data", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("date", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("dict", typeof(dict))]
    [System.Xml.Serialization.XmlElementAttribute("false", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("integer", typeof(string), DataType = "integer")]
    [System.Xml.Serialization.XmlElementAttribute("real", typeof(real))]
    [System.Xml.Serialization.XmlElementAttribute("string", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("true", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType[] ItemsElementName
    {
        get
        {
            return this.itemsElementNameField;
        }
        set
        {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class dict
{

    private string[] keyField;

    private object[] itemsField;

    private ItemsChoiceType[] itemsElementNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("key", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] key
    {
        get
        {
            return this.keyField;
        }
        set
        {
            this.keyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("array", typeof(array))]
    [System.Xml.Serialization.XmlElementAttribute("data", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("date", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("dict", typeof(dict))]
    [System.Xml.Serialization.XmlElementAttribute("false", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("integer", typeof(string), DataType = "integer")]
    [System.Xml.Serialization.XmlElementAttribute("real", typeof(real))]
    [System.Xml.Serialization.XmlElementAttribute("string", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("true", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName
    {
        get
        {
            return this.itemsElementNameField;
        }
        set
        {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class real
{

    private string[] textField;

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
public enum ItemsChoiceType
{

    /// <remarks/>
    array,

    /// <remarks/>
    data,

    /// <remarks/>
    date,

    /// <remarks/>
    dict,

    /// <remarks/>
    @false,

    /// <remarks/>
    integer,

    /// <remarks/>
    real,

    /// <remarks/>
    @string,

    /// <remarks/>
    @true,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
public enum ItemChoiceType
{

    /// <remarks/>
    array,

    /// <remarks/>
    data,

    /// <remarks/>
    date,

    /// <remarks/>
    dict,

    /// <remarks/>
    @false,

    /// <remarks/>
    integer,

    /// <remarks/>
    real,

    /// <remarks/>
    @string,

    /// <remarks/>
    @true,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
public enum ItemChoiceType1
{

    /// <remarks/>
    array,

    /// <remarks/>
    data,

    /// <remarks/>
    date,

    /// <remarks/>
    dict,

    /// <remarks/>
    @false,

    /// <remarks/>
    integer,

    /// <remarks/>
    real,

    /// <remarks/>
    @string,

    /// <remarks/>
    @true,
}
